
genesis-file = "/config/genesis.json"        #needed
node-private-key-file = "/opt/besu/keys/key" #file contain node private key default: data needed
logging = "INFO"                             # logging level, default INFO removable
data-path = "/opt/besu/data"                 #needed
host-allowlist = ["*"]                       # allow domain, default: localhost. needed
min-gas-price = 0

# permissioness
permissions-accounts-contract-enabled = true
permissions-accounts-contract-address = "0000000000000000000000000000000000000101"
# permissions-nodes-contract-enabled = true
# permissions-nodes-contract-address = "0x0000000000000000000000000000000000009999"
# permissions-nodes-contract-version = 2

# rpc
rpc-http-enabled = true # default false, needed
rpc-http-max-request-content-length = 10240
rpc-http-host = "0.0.0.0" # optional
rpc-http-port = 8545
rpc-http-cors-origins = ["*"]
rpc-http-api = [
    "WEB3",
    "ETH",
    "NET",
    "TRACE",
    "DEBUG",
    "ADMIN",
    "TXPOOL",
    "PERM",
    "QBFT",
]

# ws
rpc-ws-enabled = true
rpc-ws-host = "0.0.0.0"
rpc-ws-port = 8546
rpc-ws-api = [
    "WEB3",
    "ETH",
    "NET",
    "TRACE",
    "DEBUG",
    "ADMIN",
    "TXPOOL",
    "PERM",
    "QBFT",
]

# graphql
graphql-http-enabled = true
graphql-http-host = "0.0.0.0"
graphql-http-port = 8547
graphql-http-cors-origins = ["*"]

# metrics
metrics-enabled = true
metrics-host = "0.0.0.0"
metrics-port = 9545
